### ISSUE TITLE
looks interesting

### ISSUE THREAD

**Issue by xp12047** [Hibanaw/BCMemo#1]
How do I install it using ?  Is there documentation?  thanks, i want to try it

**Comment by Hibanaw** [comment]
It's a college course project and still on working. I will release the binary file when the most functions are finished.
To coding C/C++ under DOS, you should use Borland C++, and for nowadays operating systems, a DOSBOX is needed to emulate the MSDOS environment.
A Chinese documentation is at [Hibanaw/BCDevelopDocs](https://github.com/Hibanaw/BCDevelopDocs). I will update a "for new developers" doc today.

**Comment by xp12047** [comment]
> 这是一个大学课程项目，仍在工作中。当大多数功能完成时，我将发布二进制文件。 要在DOS下编写C/C++，你应该使用Borland C++，而对于现在的操作系统，需要一个DOSBOX来模拟MSDOS环境。 中文文档位于[Hibanaw/BCDevelopDocs](https://github.com/Hibanaw/BCDevelopDocs)。我今天将更新“面向新开发人员”的文档。

thanks
